WHITE = {1.0, 1.0, 1.0, 1.0}

DEFAULT_TABLESIZE = {1200, 120}

THREE_TABLE_TABLESIZE = {400, 120}



-- TODO - rename these when I get the new atlas

DEFAULT = "PUT_YOUR_ICON_NAME_HERE"

PRESET_IMAGES = {
    "ICON_LOKE_PIXIE_KILLER_PRESET",
    "ICON_LOKE_CINNAMONROLL_PRESET",
    "ICON_LOKE_STAINED_GLASS_PRESET",
    "ICON_LOKE_FLOWER_BOY_PRESET",
    "ICON_LOKE_DARK_URGE_PRESET",
    "ICON_LOKE_CANT_SEE_PRESET", 
    "ICON_LOKE_MR_HEALING_PRESET", 
    "ICON_LOKE_INFERNAL_PRESET",
    "ICON_LOKE_NONE"
}



FRAME_IMAGES = {
    "ICON_LOKE_FRAME",
    "ICON_LOKE_NONE"
}


ARMS_IMAGES = {
    "ICON_LOKE_ARMS",
    "ICON_LOKE_NONE"
}

CHAIN_MAIN_IMAGES = {
    "ICON_LOKE_CHAINS_MAIN",
    "ICON_LOKE_NONE"
}


FRAMES_TEXT = {
    "Frame",
    "No Frame"
}

ARMS_TEXT = {
    "Arms",
    "No Arms"
}

CHAIN_MAIN_TEXT = {
    "Chain",
    "No Chain"
}

-- Plain only exists for glasses
NAMES = {
    "Pixie Killer",
    "Cinnamonroll",
    "Stained Glass",
    "Flower Boy",
    "Dark Urge",
    "Can't See",
    "Mr Healing",
    "Infernal",
    "Nothing"
}


LENSES_IMAGES = {
    "ICON_LOKE_PIXIE_KILLER_LENSES",
    "ICON_LOKE_CINNAMONROLL_LENSES",
    "ICON_LOKE_STAINED_GLASS_LENSES",
    "ICON_LOKE_FLOWER_BOY_LENSES",
    "ICON_LOKE_DARK_URGE_LENSES",
    "ICON_LOKE_CANT_SEE_LENSES", 
    "ICON_LOKE_MR_HEALING_LENSES", 
    "ICON_LOKE_INFERNAL_LENSES",
    "ICON_LOKE_PLAIN_LENSES",
    "ICON_LOKE_NONE"
}


LENSES_NAMES = {
    "Pixie Killer",
    "Cinnamonroll",
    "Stained Glass",
    "Flower Boy",
    "Dark Urge",
    "Can't See",
    "Mr Healing",
    "Infernal",
    "Plain",
    "Nothing"
}



CHARMS_LEFT_IMAGES = {
    "ICON_LOKE_PIXIE_KILLER_CHARM_LEFT_1",
    "ICON_LOKE_CINNAMONROLL_CHARM_LEFT_1",
    "ICON_LOKE_STAINED_GLASS_CHARM_LEFT_1",
    "ICON_LOKE_FLOWER_BOY_CHARM_LEFT_1",
    "ICON_LOKE_DARK_URGE_CHARM_LEFT_1",
    "ICON_LOKE_CANT_SEE_CHARM_LEFT_1", 
    "ICON_LOKE_MR_HEALING_CHARM_LEFT_1", 
    "ICON_LOKE_INFERNAL_CHARM_LEFT_1",
     "ICON_LOKE_NONE"
}


CHARMS_RIGHT1_IMAGES = {
    "ICON_LOKE_PIXIE_KILLER_CHARM_RIGHT_1",
    "ICON_LOKE_CINNAMONROLL_CHARM_RIGHT_1",
    "ICON_LOKE_STAINED_GLASS_CHARM_RIGHT_1",
    "ICON_LOKE_FLOWER_BOY_CHARM_RIGHT_1",
    "ICON_LOKE_DARK_URGE_CHARM_RIGHT_1",
    "ICON_LOKE_CANT_SEE_CHARM_RIGHT_1", 
    "ICON_LOKE_MR_HEALING_CHARM_RIGHT_1", 
    "ICON_LOKE_INFERNAL_CHARM_RIGHT_1",
     "ICON_LOKE_NONE"
}




CHARMS_RIGHT2_IMAGES = {
    "ICON_LOKE_PIXIE_KILLER_CHARM_RIGHT_2",
    "ICON_LOKE_CINNAMONROLLCHARM_RIGHT_2",
    "ICON_LOKE_STAINED_GLASSCHARM_RIGHT_2",
    "ICON_LOKE_FLOWER_BOYCHARM_RIGHT_2",
    "ICON_LOKE_DARK_URGECHARM_RIGHT_2",
    "ICON_LOKE_CANT_SEECHARM_RIGHT_2", 
    "ICON_LOKE_MR_HEALINGCHARM_RIGHT_2", 
    "ICON_LOKE_INFERNALCHARM_RIGHT_2",
     "ICON_LOKE_NONE"
}